% Copyright (C) 1995-2010 by Hiroshi Nakashima, Yasuki Saito and
%                            The Editorial Board of the IPSJ Journal
%
% ipsjpapers.cls 28-Oct-10 by Hiroshi Nakashima (ver 3.02)
% (revision history deleted)
% ipsjpapers.cls  1-Apr-96 by Hiroshi Nakashima (ver 2.00)

\ifx\pfmtname\undefined
\NeedsTeXFormat{LaTeX2e}
\else
\NeedsTeXFormat{pLaTeX2e}
\fi

\ProvidesClass{ipsjpapers}[2010/10/28 ver 3.02]
\input{ipsjpapers.sty}
\endinput
